-- USER TRACKING TABLE
-- drop table if exists tracking;
create table if not exists tracking (
  id bigint generated by default as identity primary key,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null,
  event jsonb
);
